tag: pc1_align_ball
save_dir: outputs

network:
  zero_sum: none        # dominant PC1 regime
  seed: 15

objective:
  target_type: pc1
  axis_of_interest: color
  shape_for_color_line: 0.3

constraints:
  type: ball
  radius: 0.08
  hard_norm: true
  positive_gains: true
