tag: default_smallpc1_custom
save_dir: outputs

network:
  N: 120
  K: 2
  seed: 21
  desired_radius: 0.9
  p_high: 0.2
  p_low: 0.2
  zero_sum: row         # small PC1 regime (toggle to "none" for dominant PC1)
  wr_tuned: false
  weight_scale: 0.1

objective:
  target_type: custom_pc
  theta_deg: 30.0       # target direction in PC space
  phi_deg: 25.0
  axis_of_interest: color
  shape_for_color_line: 0.3
  color_for_shape_line: 0.3

constraints:
  type: ball            # or "box"
  radius: 0.05          # L2 ball radius = 0.10 * sqrt(N)
  box_half_width: 0.2   # used if type: box
  hard_norm: true       # keep ||axis|| equal to baseline
  positive_gains: false # set true to force g >= 0

grid:
  shape_vals: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  color_vals: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

